// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToDownloadList(arg1:string,arg2:string):Promise<void>;

export function ContinueDownload(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string):Promise<void>;

export function DownloadLoop():Promise<void>;

export function GetAbsPath(arg1:string):Promise<string>;

export function GetPlatform():Promise<string>;

export function OpenDirDialog():Promise<string>;

export function PauseDownload(arg1:string):Promise<void>;

export function RestartApp():Promise<void>;

export function UpdateApp(arg1:string):Promise<boolean>;
