// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFileDialog():Promise<string>;

export function OpenDirDialog():Promise<string>;

export function RestartApp():Promise<void>;
