// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToDownloadList(arg1, arg2) {
  return window['go']['app']['App']['AddToDownloadList'](arg1, arg2);
}

export function ContinueDownload(arg1) {
  return window['go']['app']['App']['ContinueDownload'](arg1);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['app']['App']['DownloadFile'](arg1, arg2);
}

export function DownloadLoop() {
  return window['go']['app']['App']['DownloadLoop']();
}

export function GetAbsPath(arg1) {
  return window['go']['app']['App']['GetAbsPath'](arg1);
}

export function GetPlatform() {
  return window['go']['app']['App']['GetPlatform']();
}

export function OpenDirDialog() {
  return window['go']['app']['App']['OpenDirDialog']();
}

export function PauseDownload(arg1) {
  return window['go']['app']['App']['PauseDownload'](arg1);
}

export function RestartApp() {
  return window['go']['app']['App']['RestartApp']();
}

export function UpdateApp(arg1) {
  return window['go']['app']['App']['UpdateApp'](arg1);
}
