// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirDialog() {
  return window['go']['app']['App']['OpenDirDialog']();
}

export function RestartApp() {
  return window['go']['app']['App']['RestartApp']();
}

export function UpdateApp(arg1) {
  return window['go']['app']['App']['UpdateApp'](arg1);
}
